version: '3'

services:
  node:
    build: .
    ports:
      - 8000:8000
    environment:
      - PORT=8000
    links:
     - mongodb
      
  mongodb:
    image: mongo
    container_name: mongo-leaf
    environment:
      MONGO_INITDB_DATABASE: lab
      MONGO_INITDB_ROOT_USERNAME: self
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
      